version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.1.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.1.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    command: redis-server --protected-mode no --port 6379 --save 60 1000
    volumes:
      - redis:/data

volumes:
  redis: